# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 06:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='user_rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1)]),
        ),
    ]
