# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_post', '0004_auto_20180504_0613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
    ]
